#!/bin/sh

echo "-----------------------------------------"
echo "Executing ...deploy... user action hook"
echo "-----------------------------------------"


echo "-----------------------------------------"
echo "Finishing ...deploy... user action hook"
echo "-----------------------------------------"
