#!/bin/bash

echo "-----------------------------------------"
echo "Executing ...stop... user action hook"
echo "-----------------------------------------"



echo "-----------------------------------------"
echo "Finishing ...stop... user action hook"
echo "-----------------------------------------"
